#!/usr/bin/env python3
import connexion
import sys
from werkzeug.wsgi import pop_path_info, peek_path_info
from werkzeug.serving import run_simple

from .ui import app as frontend_app
from .backend import backend_app, api_app


class PathDispatcher(object):
    def __init__(self, api_app, frontend_app):
        self.api_app = api_app
        self.frontend_app = frontend_app

    def get_application(self, prefix):
        print("prefix=", repr(prefix))
        if prefix == "api":
            return self.api_app
        else:
            return self.frontend_app

    def __call__(self, environ, start_response):
        app = self.get_application(peek_path_info(environ))
        return app(environ, start_response)





def main():
    debug = True

    api_app.add_api('swagger.yaml',
                    arguments={
                        'title': 'No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)'})

    application = PathDispatcher(api_app, frontend_app)

    run_simple('localhost', 8080, application,
               use_reloader=True, use_debugger=debug, use_evalex=True)
