#!/usr/bin/env python3
from . import persist
import connexion
import sys
from werkzeug.wsgi import pop_path_info, peek_path_info
from werkzeug.serving import run_simple

from .ui import app as frontend_app
from .backend import backend_app, api_app


class PathDispatcher(object):
    def __init__(self, api_app, frontend_app):
        self.api_app = api_app
        self.frontend_app = frontend_app

    def get_application(self, prefix):
        print("prefix=", repr(prefix))
        if prefix == "api":
            return self.api_app
        else:
            return self.frontend_app

    def __call__(self, environ, start_response):
        app = self.get_application(peek_path_info(environ))
        # print("delegating {} to {}".format(environ, app))
        # pop_path_info(environ)
        return app(environ, start_response)





def main():
    debug = True

    #    logging.basicConfig()
    #    l = logging.getLogger("connexion")
    #    l.setLevel(logging.DEBUG)

    # API app configuration
    # api_app = connexion.App(__name__, specification_dir='./swagger/')

    db = persist.open_db(sys.argv[1])

    api_app.db = db

    api_app.add_api('swagger.yaml',
                    # validate_responses=debug,
                    arguments={
                        'title': 'No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)'})

    application = PathDispatcher(api_app, frontend_app)

    run_simple('localhost', 8080, application,
               use_reloader=True, use_debugger=debug, use_evalex=True)
