# Command to trigger travis on all branches having a .travis.ymll
branches:
  only:
    - /.*/
notifications:
  email:
    recipients:
      - rmarenco@broadinstitute.org
      - pmontgom@broadinstitute.org
language: python
python:
  - "3.6"
# Command to install dependencies
install:
  - sh write_version.sh
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  # Replace dep1 dep2 ... with your dependencies
  - conda create -q -n test-environment -c bioconda python=$TRAVIS_PYTHON_VERSION bioconductor-rhdf5 numpy=1.11.3
  - source activate test-environment
  - pip install -U pip setuptools
  - python setup.py install
  # Add the aws cli for docker build/push
  - pip install -r requirements.txt
  - pip install awscli

services:
  - docker

# Command to run tests
script:
  - pytest

after_success:
  # After tests have been successful, we build a new docker image and push it to ECR
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      chmod ugo+x build_docker.sh;
      ./build_docker.sh;
      chmod ugo+x travis/push_docker.sh;
      travis/push_docker.sh;
    fi
