#!/usr/bin/env python3
import sys
import persist
import connexion

if __name__ == '__main__':
    app = connexion.App(__name__, specification_dir='./swagger/')
    app.app.db = persist.open_db(sys.argv[1])
    print(repr(app))
    debug = True
    app.add_api('swagger.yaml', 
        validate_responses=debug,
        arguments={'title': 'No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)'})
    app.run(port=8080, debug=debug)

