"""empty message

Revision ID: 42d37b47160c
Revises: 9c0d7f0a89e8
Create Date: 2018-09-12 14:04:00.510194

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '42d37b47160c'
down_revision = '9c0d7f0a89e8'
branch_labels = None
depends_on = None


def upgrade():
    dataset_version_state = postgresql.ENUM('approved', 'deprecated', 'deleted', name='datasetversionstate')
    dataset_version_state.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset_versions', sa.Column('reason_state', sa.Text(), nullable=True))
    op.add_column('dataset_versions', sa.Column('state', sa.Enum('approved', 'deprecated', 'deleted', name='datasetversionstate'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dataset_versions', 'state')
    op.drop_column('dataset_versions', 'reason_state')
    # ### end Alembic commands ###
    dataset_version_state = postgresql.ENUM('approved', 'deprecated', 'deleted', name='datasetversionstate')
    dataset_version_state.drop(op.get_bind())