"""add-compressed-field

Revision ID: 6bf0d302380c
Revises: 946c898fcded
Create Date: 2020-02-12 10:58:23.610440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6bf0d302380c"
down_revision = "946c898fcded"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "datafiles", sa.Column("column_types_as_json", sa.JSON(), nullable=True)
    )
    op.add_column("datafiles", sa.Column("compressed_s3_key", sa.Text(), nullable=True))
    op.add_column("datafiles", sa.Column("encoding", sa.Text(), nullable=True))
    op.add_column("datafiles", sa.Column("original_file_md5", sa.Text(), nullable=True))
    op.add_column(
        "upload_session_files",
        sa.Column("column_types_as_json", sa.JSON(), nullable=True),
    )
    op.add_column(
        "upload_session_files", sa.Column("compressed_s3_key", sa.Text(), nullable=True)
    )
    op.add_column(
        "upload_session_files", sa.Column("encoding", sa.Text(), nullable=True)
    )
    op.add_column(
        "upload_session_files", sa.Column("original_file_md5", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("upload_session_files", "original_file_md5")
    op.drop_column("upload_session_files", "encoding")
    op.drop_column("upload_session_files", "compressed_s3_key")
    op.drop_column("upload_session_files", "column_types_as_json")
    op.drop_column("datafiles", "original_file_md5")
    op.drop_column("datafiles", "encoding")
    op.drop_column("datafiles", "compressed_s3_key")
    op.drop_column("datafiles", "column_types_as_json")
    # ### end Alembic commands ###
