swagger: '2.0'
info:
  version: 1.0.0
  title: Taiga
basePath: /api
schemes:
  - http
  - https
consumes:
  - application/json
  - text/xml
produces:
  - application/json
  - text/html
paths:
  /folder/{folderId}:
    get:
      x-swagger-router-controller: taiga2.controllers.default_controller
      operationId: get_folder
      description: Fetch the details and content of a folder by id
      parameters:
        - name: folderId
          in: path
          type: string
          description: Folder ID
          required: true
      responses:
        200:
          description:  Properties of requested folder
          schema:
            title: Folder
            type: object
            required: 
              - id
              - name
              - type
              - parents
              - entries
              - creation_date
              - creator
            properties:
              id: 
                type: string
              name: 
                type: string
              type:
                type: string
                enum:
                  - folder
                  - trash
                  - home
              parents: 
                type: array
                items: 
                  "$ref": "#/definitions/NamedId"
              creation_date:
                type: string
              creator:
                "$ref": "#/definitions/NamedId"
              description:
                type: string
              entries:
                type: array
                items: 
                  type: object
                  required:
                    - type
                    - id
                    - name
                    - creation_date
                    - creator
                  properties:
                    type:
                      type: string
                      enum:
                        - folder
                        - dataset
                        - dataset_version
                    id:
                      type: string
                    # populated for dataset and datasetVersion.  Useful to know what the latest version of a dataset is.
                    dataset_version_id:
                      type: string
                    name:
                      type: string
                    creation_date:
                      type: string
                    creator:
                      "$ref": "#/definitions/NamedId"

  /folders/create:
    post:
      x-swagger-router-controller: taiga2.controllers.default_controller
      operationId: create_folder
      description: Create a new folder
      parameters:
        - in: body
          name: metadata
          schema:
            type: object
            required:
              - name
              - parent
            properties:
              name:
                type: string
                description: New folder name
              description:
                type: string
                description: Long description
              parent:
                type: string
                description: Parent folder ID to initially insert this folder under
      responses:
        200:
          description: The id of the newly created folder
          schema:
            title: CreateFolderResponse
            type: object
            required: 
              - id
              - name
            properties:
              id: 
                type: string
              name: 
                type: string


  /folders/update:
    post:
      x-swagger-router-controller: taiga2.controllers.default_controller
      operationId: update_folders
      description: Perform multiple updates to folders within a single transaction.  Can be used for moves (a remove and add somewhere else), copies (and add) and deletes (a remove and add to trash)
      parameters:
        - in: body
          name: operations
          schema:
            type: object
            properties:
              operations:
                type: array
                items:
                  type: object
                  required:
                    - parent
                    - opType
                    - idType
                    - id
                  properties:
                    parent: 
                      type: string
                    opType:
                      type: string
                      enum: 
                        - add
                        - remove
                    idType:
                      type: string
                      enum:
                        - folder
                        - dataset
                        - datasetVersion
                    id:
                      type: string
      responses:
        200:
          description: Successful execution of update
        400:
          description: Attempted to do something bad (move trash or home, or modify non-existant entry)

          
  /user:
    get:
      x-swagger-router-controller: taiga2.controllers.default_controller
      operationId: get_user
      description: Fetch properties about the currently authenticated user
      responses:
        200:
          description: Properties of current user
          schema:
            title: User
            type: object
            required:
              - id
              - name
              - home_folder_id
              - trash_folder_id
            properties:
              id: 
                type: string
              name:
                type: string
              home_folder_id:
                type: string
              trash_folder_id:
                type: string

  /uploadurl:
    get:
      x-swagger-router-controller: taiga2.controllers.default_controller
      operationId: get_upload_url
      description: Get url used to upload data
      responses:
        200:
          description: Url and id to use to refer to upload location
          schema:
            title: FileUploadInfo
            type: object
            required: 
              - id
              - url
            properties:
              id:
                type: string
              url:
                type: string

  /dataset:
    post:
      x-swagger-router-controller: taiga2.controllers.default_controller
      operationId: create_dataset
      description: Create a dataset from a set of already uploaded objects
      parameters:
        - in: body
          name: DatasetDefinition
          schema:
            type: object
            required:
              - name
              - parent
              - entries
            properties:
              name:
                type: string
              description:
                type: string
              parent:
                type: string
              entries:
                type: array
                items:
                  "$ref": "#/definitions/DataFileSubmission"
      responses:
        200:
          description: The info about the newly created dataset
          schema:
            "$ref": "#/definitions/ImportStatus"
  
  /dataset/{datasetId}:
    get:
      x-swagger-router-controller: taiga2.controllers.default_controller
      operationId: get_dataset
      description: Fetch the details of a dataset
      parameters:
        - name: datasetId
          in: path
          type: string
          description: Dataset ID
          required: true
      responses:
        200:
          description: The data specific to a specific dataset
          schema:
            title: Dataset
            type: object
            required: 
              - id
              - name
              - description
              - permanames
              - versions
            properties:
              id:
                type: string
              name:
                type: string
              permanames:
                type: array
                items:
                  type: string
              description:
                type: string
              versions:
                type: array
                items:
                  title: DatasetVersionSummary
                  type: object
                  required:
                    - name
                    - id
                    - status
                  properties:
                    name: 
                      type: string
                    id:
                      type: string
                    status:
                      "$ref": "#/definitions/StatusEnum"

  /dataset/{datasetId}/version:
    post:
      x-swagger-router-controller: taiga2.controllers.default_controller
      operationId: update_dataset
      description: Create a new dataset version by updating the data files associated with dataset.
      parameters:
        - name: datasetId
          in: path
          type: string
          description: Folder ID
          required: true
        - in: body
          name: DatasetUpdate
          schema:
            type: object
            properties:
              old_entries:
                description: The names of data files to remove.
              new_entries:
                description: Data files to add as part of the new version.
                type: array
                items:
                  "$ref": "#/definitions/DataFileSubmission"
      responses:
        200:
          description: The info about the newly created dataset
          schema:
            "$ref": "#/definitions/ImportStatus"

  /dataset/{datasetId}/activity:
    get:
      x-swagger-router-controller: taiga2.controllers.default_controller
      operationId: get_dataset_activity
      description: Fetch activity history for this dataset
      parameters:
        - name: datasetId
          in: path
          type: string
          description: Dataset ID
          required: true
      responses:
        200:
          description: Successfully updated

  /dataset/{datasetId}/name:
    post:
      x-swagger-router-controller: taiga2.controllers.default_controller
      operationId: update_dataset_name
      description: Update dataset name
      parameters:
        - name: datasetId
          in: path
          type: string
          description: Dataset ID
          required: true
      responses:
        200:
          description: Successfully updated

  /dataset/{datasetId}/description:
    post:
      x-swagger-router-controller: taiga2.controllers.default_controller
      operationId: update_dataset_description
      description: Update dataset name
      parameters:
        - name: datasetId
          in: path
          type: string
          description: Dataset ID
          required: true
      responses:
        200:
          description: Successfully updated

  /datasetVersion/{datasetVersionId}:
    get:
      x-swagger-router-controller: taiga2.controllers.default_controller
      operationId: get_dataset_version
      description: Fetch the contents of a version of specific dataset
      parameters:
        - name: datasetVersionId
          in: path
          type: string
          description: Dataset Version ID
          required: true
      responses:
        200:
          description: The data specific to a specific dataset version
          schema:
            title: DatasetVersion
            type: object
            required: 
              - id
              - dataset_id
              - name
              - creation_date
              - creator
              - datafiles
              - version
              - folders
            properties:
              id:
                type: string
              folders:
                type: array
                items:
                  "$ref": "#/definitions/NamedId"
              dataset_id:
                type: string
              status:
                "$ref": "#/definitions/StatusEnum"
              name:
                type: string
              version:
                type: string
              description:
                type: string
              creation_date:
                type: string
              creator:
                "$ref": "#/definitions/NamedId"
              datafiles:
                type: array
                items:
                  title: DataFile
                  type: object
                  required:
                    - name
                    - url
                    - mime_type
                    - description
                    - content_summary
                  properties:
                    name: 
                      type: string
                    url:
                      type: string
                    mime_type:
                      type: string
                    description:
                      type: string
                    content_summary:
                      description: "A textual description of the size.  (ie: '200 x 30 table')  Should be relatively short and summarize the shape/size of the contents."
                      type: string
            
  /datasetVersion/{datasetVersionId}/status:
    get:
      x-swagger-router-controller: taiga2.controllers.default_controller
      operationId: get_dataset_version_status
      description: Fetch the status of a dataset being imported
      parameters:
        - name: datasetVersionId
          in: path
          type: string
          description: Dataset Version ID
          required: true
      responses:
        200:
          description: Status of import, and any error which may have occurred
          schema:
            "$ref": "#/definitions/ImportStatus"

  /datafile:
    get:
      x-swagger-router-controller: taiga2.controllers.default_controller
      operationId: get_datafile
      # do we need to support conversion?
      description: Get datafile contents
      parameters:
        - name: name
          in: query
          type: string
          description: dataset_id or dataset_version_id with optional version number and filename
          required: true
      responses:
        200:
          description: Successfully updated


#missing provenance

definitions:
  DataFileSubmission:
    type: object
    required:
      - name
      - id
    properties:
      name:
        type: string
      mime_type:
        type: string
      description:
        type: string
      id:
        type: string
        description: The object ID returned from the /uploadurl request
  
  ImportStatus:
    type: object
    required:
      - dataset_version_id
      - status
      - message
    properties:
      dataset_version_id:
        type: string
        description: The id of the datasetVersion that is being created.  Additionally, this id can be used in polling when a dataset import is not yet complete.
      status:
        description: 'One of "pending", "running", "completed" or "failed".  If completed, there will exist a new datasetVersion with id specified in this response.  Failures should have the reason included in the status message.'
        type: string
        enum:
          - pending
          - running
          - complete
          - failed
      message:
        description: Human readable summary of the progress of the import
        type: string

  NamedId:
    type: object
    properties:
      name:
        type: string
      id:
        type: string

  StatusEnum:
    type: string
    enum: 
      - deprecated # Discourage use.  Warn when fetching
      - deleted    # Underlying data has been deleted
      - valid

