"""update-started-log

Revision ID: 2af60fdf97d1
Revises: c9d2700c78d4
Create Date: 2019-07-18 16:50:09.398289

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "2af60fdf97d1"
down_revision = "c9d2700c78d4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    op.execute("delete from activities")
    op.execute("""
        INSERT into activities (id, user_id, dataset_id, type, dataset_name, dataset_description, dataset_version, timestamp)
        SELECT uuid_in(md5(random()::text || clock_timestamp()::text)::cstring), u.id, v.dataset_id, 'started_log', de.name, ve.description, v.version, CURRENT_TIMESTAMP
        FROM dataset_versions v
        JOIN datasets d ON v.dataset_id = d.id
        JOIN entries ve ON ve.id = v.id
        JOIN entries de on de.id = d.id,
        users u
        WHERE u.name = 'admin'
    """)
    op.execute("update entries set description = null where type = 'Dataset'")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    op.execute("delete from activities")
