"""empty message

Revision ID: 90837b08919f
Revises: 2d1729557360
Create Date: 2022-06-02 11:46:11.207267

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "90837b08919f"
down_revision = "2d1729557360"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lock_table",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("random", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lock_table")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("lock_table")
    # ### end Alembic commands ###
