"""empty message

Revision ID: 9552e419c662
Revises: 1cde9ea7a48f
Create Date: 2017-04-20 16:23:31.868786

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "9552e419c662"
down_revision = "1cde9ea7a48f"
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        "provenance_graphs",
        sa.Column("graph_id", sa.String(length=80), nullable=False),
        sa.Column("permaname", sa.String(length=80), nullable=True),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("created_by_user_id", sa.String(length=80), nullable=True),
        sa.Column("created_timestamp", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_provenance_graphs_created_by_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("graph_id", name=op.f("pk_provenance_graphs")),
        sa.UniqueConstraint("permaname", name=op.f("uq_provenance_graphs_permaname")),
    )
    op.create_table(
        "provenance_nodes",
        sa.Column("node_id", sa.String(length=80), nullable=False),
        sa.Column("graph_id", sa.String(length=80), nullable=True),
        sa.Column("dataset_version_id", sa.String(length=80), nullable=True),
        sa.Column("label", sa.Text(), nullable=True),
        sa.Column(
            "type",
            sa.Enum("Dataset", "External", "Process", name="nodetype"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["dataset_version_id"],
            ["dataset_versions.id"],
            name=op.f("fk_provenance_nodes_dataset_version_id_dataset_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["graph_id"],
            ["provenance_graphs.graph_id"],
            name=op.f("fk_provenance_nodes_graph_id_provenance_graphs"),
        ),
        sa.PrimaryKeyConstraint("node_id", name=op.f("pk_provenance_nodes")),
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "provenance_edges",
        sa.Column("edge_id", sa.String(length=80), nullable=False),
        sa.Column("from_node_id", sa.String(length=80), nullable=True),
        sa.Column("to_node_id", sa.String(length=80), nullable=True),
        sa.Column("label", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["from_node_id"],
            ["provenance_nodes.node_id"],
            name=op.f("fk_provenance_edges_from_node_id_provenance_nodes"),
        ),
        sa.ForeignKeyConstraint(
            ["to_node_id"],
            ["provenance_nodes.node_id"],
            name=op.f("fk_provenance_edges_to_node_id_provenance_nodes"),
        ),
        sa.PrimaryKeyConstraint("edge_id", name=op.f("pk_provenance_edges")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("provenance_edges")
    op.drop_table("provenance_nodes")
    op.drop_table("provenance_graphs")
    # ### end Alembic commands ###
