"""empty message

Revision ID: a286182fdf59
Revises: c605b801f114
Create Date: 2022-06-06 14:28:10.165108

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "a286182fdf59"
down_revision = "c605b801f114"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("INSERT INTO lock_table VALUES (0, 50)")
    op.create_table(
        "read_access_log",
        sa.Column("datafile_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("first_access", sa.DateTime(), nullable=True),
        sa.Column("last_access", sa.DateTime(), nullable=True),
        sa.Column("access_count", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint(
            "datafile_id", "user_id", name=op.f("pk_read_access_log")
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("read_access_log")
    # ### end Alembic commands ###
