"""empty message

Revision ID: c605b801f114
Revises: ddeac9a40a1c
Create Date: 2022-06-06 11:24:24.010508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c605b801f114"
down_revision = "ddeac9a40a1c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lock_table",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("random", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lock_table")),
    )
    op.execute("INSERT INTO lock_table VALUES (0, 50)")
    op.create_table(
        "read_access_log",
        sa.Column("datafile_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("first_access", sa.DateTime(), nullable=True),
        sa.Column("last_access", sa.DateTime(), nullable=True),
        sa.Column("access_count", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint(
            "datafile_id", "user_id", name=op.f("pk_read_access_log")
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("read_access_log")
    op.drop_table("lock_table")
    # ### end Alembic commands ###
