"""empty message

Revision ID: c605b801f114
Revises: ddeac9a40a1c
Create Date: 2022-06-06 11:24:24.010508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c605b801f114"
down_revision = "ddeac9a40a1c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
