"""add-activity-log2

Revision ID: c9d2700c78d4
Revises: 6d8d4536fb51
Create Date: 2019-07-17 17:14:17.166376

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c9d2700c78d4"
down_revision = "6d8d4536fb51"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    op.execute("update activities set timestamp = (select CURRENT_TIMESTAMP)")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    pass
