"""empty message

Revision ID: ddeac9a40a1c
Revises: 90837b08919f
Create Date: 2022-06-06 11:08:07.514116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ddeac9a40a1c"
down_revision = "90837b08919f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
