"""add figshare-integration

Revision ID: e04e7eb4fb16
Revises: 6bf0d302380c
Create Date: 2020-03-11 11:46:54.150090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e04e7eb4fb16"
down_revision = "6bf0d302380c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "figshare_authorizations",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("user_id", sa.String(length=80), nullable=True),
        sa.Column("figshare_account_id", sa.Integer(), nullable=True),
        sa.Column("token", sa.Text(), nullable=False),
        sa.Column("refresh_token", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_figshare_authorizations_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_figshare_authorizations")),
    )
    op.create_table(
        "third_party_datafile_links",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_third_party_datafile_links")),
    )
    op.create_table(
        "third_party_dataset_version_links",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=True),
        sa.Column("creator_id", sa.String(length=80), nullable=True),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["users.id"],
            name=op.f("fk_third_party_dataset_version_links_creator_id_users"),
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_third_party_dataset_version_links")
        ),
    )
    op.create_table(
        "figshare_dataset_version_links",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("figshare_article_id", sa.Integer(), nullable=False),
        sa.Column("dataset_version_id", sa.String(length=80), nullable=True),
        sa.ForeignKeyConstraint(
            ["dataset_version_id"],
            ["dataset_versions.id"],
            name=op.f(
                "fk_figshare_dataset_version_links_dataset_version_id_dataset_versions"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["id"],
            ["third_party_dataset_version_links.id"],
            name=op.f(
                "fk_figshare_dataset_version_links_id_third_party_dataset_version_links"
            ),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_figshare_dataset_version_links")),
    )
    op.create_table(
        "figshare_datafile_links",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("figshare_file_id", sa.Integer(), nullable=False),
        sa.Column("datafile_id", sa.String(length=80), nullable=True),
        sa.Column(
            "figshare_dataset_version_link_id", sa.String(length=80), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["datafile_id"],
            ["datafiles.id"],
            name=op.f("fk_figshare_datafile_links_datafile_id_datafiles"),
        ),
        sa.ForeignKeyConstraint(
            ["figshare_dataset_version_link_id"],
            ["figshare_dataset_version_links.id"],
            name=op.f(
                "fk_figshare_datafile_links_figshare_dataset_version_link_id_figshare_dataset_version_links"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["id"],
            ["third_party_datafile_links.id"],
            name=op.f("fk_figshare_datafile_links_id_third_party_datafile_links"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_figshare_datafile_links")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("third_party_dataset_version_links")
    op.drop_table("third_party_datafile_links")
    op.drop_table("figshare_dataset_version_links")
    op.drop_table("figshare_datafile_links")
    op.drop_table("figshare_authorizations")
    # ### end Alembic commands ###
