"""empty message

Revision ID: f8856168298f
Revises: 028f07e95137
Create Date: 2017-07-19 16:20:47.984794

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "f8856168298f"
down_revision = "028f07e95137"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("uq_datafiles_dataset_version_id"),
        "datafiles",
        ["dataset_version_id", "name"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_datafiles_dataset_version_id"), "datafiles", type_="unique"
    )
    # ### end Alembic commands ###
